var colors = require('colors');

var exampleTMR = {'Step': 'final',
'results': [{'TMR': {'ANIMAL-1': {'EXPERIENCER-OF': 'BEAR-OFFSPRING-1',
 'GENDER': 'FEMALE',
'concept': 'ANIMAL',
'from-sense': 'SHE-N1',
 'token': 'She',
 'word-ind': 0},
 'BEAR-OFFSPRING-1': {'EXPERIENCER': 'ANIMAL-1',
 'THEME': 'OFFSPRING-1',
 'concept': 'BEAR-OFFSPRING',
 'from-sense': 'BEAR-V1',
 'syn-roles': ['SUBJECT',
 'DIRECTOBJECT'],
 'token': 'bears',
 'word-ind': 1},
 'OFFSPRING-1': {'GENDER': 'MALE',
 'THEME-OF': 'BEAR-OFFSPRING-1',
 'concept': 'OFFSPRING',
 'from-sense': 'SON-N1',
 'token': 'son',
'word-ind': 3}},
 'concept_counts': {'ANIMAL': {'count': 1,
 'word-ind': [0]},
 'BEAR-OFFSPRING': {'count': 1,
 'word-ind': [1]},
 'OFFSPRING': {'count': 1,
 'word-ind': [3]}},
 'words': {'0': 'SHE-N1', '1': 'BEAR-V1', '3': 'SON-N1'}}],
'sent-num': 1,
'sentence': 'She bears a son.',
'timestamp': '2016-Jan-20 18:44:13'};


var inverses = {
'BELONGS-TO': 'POSSESSES',
'POSSESSES': 'BELONGS-TO',
'HAS-GRANDCHILD': 'HAS-GRANDPARENT',
'BEHIND': 'IN-FRONT-OF',
'EVALUATED-ACCORDING-TO': 'EVALUATION-STANDARD-FOR',
'CITY-OF-BIRTH-OF': 'HAS-CITY-OF-BIRTH',
'HAS-NAME-SUFFIX': 'NAME-OF',
'HAS-CENTER': 'CENTER-OF',
'SERVICES-OF': 'RELATION',
'MEASURING-DEVICE-FOR': 'MEASURED-BY',
'LANGUAGE-OF': 'LANGUAGE-USED',
'POSTAL-CODE-OF': 'HAS-POSTAL-CODE',
'PART-OF-EVENT': 'HAS-EVENT-AS-PART',
'PRECONDITION-OF': 'PRECONDITION',
'LANGUAGE-RELATION': 'RELATION',
'BORDERS-ON': 'BORDERS',
'EQUALS': 'EQUAL-TO',
'USES': 'USED-BY',
'LEFT-OF': 'RIGHT-OF',
'HAS-HEADQUARTERS': 'HEADQUARTERS-OF',
'OBJECT-INVOLVED': 'RELATION',
'HAS-REPRESENTATIVE': 'REPRESENTATIVE-OF',
'UP-DIRECTIONAL': 'RELATION',
'THEME-OF': 'THEME',
'INVERSE': 'INVERSE-OF',
'PAST-DISEASE-OF': 'HAS-DISEASE-HISTORY',
'REASON': 'RELATION',
'PHONE-NUMBER-OF': 'HAS-PHONE-NUMBER',
'AGENT': 'AGENT-OF',
'HAS-OBJECT-AS-PART': 'PART-OF-OBJECT',
'IN-FRONT-OF': 'BEHIND',
'COREFER': 'COREFER',
'ADDRESS-OF': 'HAS-STREET-ADDRESS',
'OUTSIDE-OF': 'RELATION',
'HAS-NAME-PREFIX': 'NAME-OF',
'DEPICTS': 'DEPICTED-BY',
'SPEAKS-LANGUAGE': 'LANGUAGE-SPOKEN-BY',
'ABOUT-AS-TOPIC': 'TOPIC-OF',
'MEASURED-BY': 'MEASURING-DEVICE-FOR',
'SURROUNDS': 'SURROUNDED-BY',
'COACH-OF': 'HAS-COACH',
'HAS-SOCIAL-ROLE': 'RELATION',
'HAS-POSTAL-CODE': 'POSTAL-CODE-OF',
'WINNER-OF': 'HAS-WINNER',
'MEMBER-OF': 'HAS-MEMBER',
'HAS-COMPETITOR': 'RELATION',
'PRECONDITION': 'PRECONDITION-OF',
'EFFECT': 'CAUSED-BY',
'ENCLOSES': 'INSIDE-OF',
'NOT-ELEMENTS': 'RELATION',
'CUSTOMARY-FOR': 'ACCUSTOMED-TO',
'AREA-OF-BUSINESS-ACTIVITY': 'ORGANIZATION-IN-BUSINESS-AREA',
'STANDARD-MEASURE-FOR': 'HAS-STANDARD-MEASURE',
'EAST-OF': 'RELATION',
'SUBCLASSES': 'IS-A',
'PRODUCED-BY': 'PRODUCER-OF',
'SURROUNDED-BY': 'SURROUNDS',
'USED-IN': 'INVOLVES-OBJECT',
'BEYOND': 'RELATION',
'PRODUCER-OF': 'PRODUCED-BY',
'LESS-THAN': 'GREATER-THAN',
'BIRTH-INFO-OF': 'HAS-BIRTH-INFO',
'AREA-STUDIED-BY-FIELD': 'FIELD-STUDIES-AREA',
'AGENT-OF': 'AGENT',
'MEMBER-TYPE': 'RELATION',
'MEASURING-UNIT-FOR': 'MEASURED-IN',
'HAS-CITY-ADDRESS': 'CITY-ADDRESS-OF',
'HAS-IN-LAW': 'IN-LAW-OF',
'PART-OF-OBJECT': 'HAS-OBJECT-AS-PART',
'PURPOSE-OF': 'PURPOSE',
'HAS-CURRENCY': 'CURRENCY-OF',
'ALTERNATIVE-OF': 'ALTERNATIVE',
'MANUFACTURED-BY': 'MANUFACTURER-OF',
'HAS-WEB-ADDRESS': 'RELATION',
'HAS-SPORTS-ACTIVITY': 'RELATION',
'FUNCTIONS-ALIKE': 'FUNCTIONS-LIKE',
'BESIDE': 'RELATION',
'ENABLED-BY': 'ENABLEMENT',
'SUPERORDINATE-TO': 'SUBORDINATE-TO',
'ALTERNATIVE': 'ALTERNATIVE-OF',
'HAS-ADDRESS': 'ADDRESS-OF',
'CELEBRATES': 'CELEBRATED-IN',
'EXPERIENCER-OF': 'EXPERIENCER',
'ABSOLUTE-DAY-OF-THE-WEEK': 'RELATION',
'HAS-STREET-ADDRESS': 'ADDRESS-OF',
'MEASURES-PROPERTY': 'PROPERTY-MEASURED',
'MIDDLE-INITIAL-OF': 'HAS-MIDDLE-INITIAL',
'IS-A': 'SUBCLASSES',
'TARGETED-BY-MEDICAL-TEST': 'MEDICAL-TEST-TARGET',
'CONTRARY-TO-EXPECTATION-BECAUSE-OF': 'HAS-UNEXPECTED-OUTCOME',
'HAS-EARTH-RESOURCE': 'EARTH-RESOURCE-OF',
'DISTANT-FAMILY-RELATION-OF': 'HAS-DISTANT-FAMILY-RELATION',
'MATERIAL-OF': 'MADE-OF',
'MEET': 'RELATION',
'HAS-NATIONALITY': 'NATIONALITY-OF',
'GEOPOLITICAL-RELATION': 'RELATION',
'INSIDE-OF': 'ENCLOSES',
'CENTER-OF': 'HAS-CENTER',
'EMAIL-ADDRESS-OF': 'HAS-EMAIL-ADDRESS',
'HAS-SURNAME': 'NAME-OF',
'HAS-MIDDLE-NAME': 'NAME-OF',
'UNDER': 'ABOVE',
'BETWEEN-SPATIAL': 'RELATION',
'SIBLING-OF': 'HAS-SIBLING',
'HAS-MEMBER': 'MEMBER-OF',
'CURRENCY-OF': 'HAS-CURRENCY',
'NATIONALITY-OF': 'HAS-NATIONALITY',
'CORPORATE-ASSETS-OF': 'RELATION',
'FIELD-CORRESPONDS-TO-JOB': 'JOB-CORRESPONDS-TO-FIELD',
'HAS-RELIGION': 'RELIGION-OF',
'SPORTS-RELATION': 'RELATION',
'MEDICAL-RISK-OF': 'HAS-MEDICAL-RISK',
'AFTER': 'BEFORE',
'ACROSS': 'ACROSS-FROM',
'HAS-REFEREE': 'REFEREE-OF',
'HAS-PARENT': 'HAS-OFFSPRING',
'VENOUS-DRAINAGE': 'VENOUS-DRAINAGE-FOR',
'SPATIAL-PATH': 'RELATION',
'HAS-AGRICULTURAL-PRODUCT': 'AGRICULTURAL-PRODUCT-OF',
'HAS-FRANCHISE': 'FRANCHISE-OF',
'NOTES': 'RELATION',
'ABOVE': 'UNDER',
'HAS-UNEXPECTED-OUTCOME': 'CONTRARY-TO-EXPECTATION-BECAUSE-OF',
'HAS-GOVERNMENT-TYPE': 'GOVERNMENT-OF',
'HAS-INDUSTRY': 'INDUSTRY-OF',
'PROXIMAL-TO': 'DISTAL-TO',
'HAS-SIBLING': 'SIBLING-OF',
'HAS-EVENT-AS-PART': 'PART-OF-EVENT',
'INSTANCES': 'INSTANCE-OF',
'BUSINESS-RELATION': 'RELATION',
'EQUAL-TO': 'EQUALS',
'OBJECT-RELATION': 'RELATION',
'ON-TOP-OF': 'BELOW-AND-TOUCHING',
'HAS-CHIEF-EXECUTIVE-OFFICER': 'RELATION',
'HAS-GRANDPARENT': 'HAS-GRANDCHILD',
'OPERATED-BY': 'OPERATOR-OF',
'NORTH-OF': 'RELATION',
'INSTRUMENT-OF': 'INSTRUMENT',
'ALIAS-OF': 'HAS-ALIAS',
'HAS-OCCUPANT': 'OCCUPANT-OF',
'BELOW-AND-TOUCHING': 'ON-TOP-OF',
'DEFINITION': 'RELATION',
'ORGANIZATION-IN-BUSINESS-AREA': 'AREA-OF-BUSINESS-ACTIVITY',
'UPPER-LIMIT-OF': 'HAS-UPPER-LIMIT',
'HOLDING-COMPANY-OF': 'HAS-HOLDING-COMPANY',
'FAMILY-RELATION': 'RELATION',
'FAX-NUMBER-OF': 'HAS-FAX-NUMBER',
'RELATION': 'RELATION',
'BEFORE': 'AFTER',
'DOMAIN': 'DOMAIN-OF',
'CITY-ADDRESS-OF': 'HAS-CITY-ADDRESS',
'HAS-ALIAS': 'ALIAS-OF',
'DISTAL-TO': 'PROXIMAL-TO',
'MADE-OF': 'MATERIAL-OF',
'RULES': 'RELATION',
'GOAL': 'RELATION',
'VENOUS-DRAINAGE-FOR': 'VENOUS-DRAINAGE',
'ARTERIAL-SUPPLY': 'ARTERIAL-SUPPLY-FOR',
'HAS-CUSTOMER': 'CUSTOMER-OF',
'SPATIAL-RELATION': 'RELATION',
'HAS-NAME': 'NAME-OF',
'RIGHT-OF': 'LEFT-OF',
'HAS-MIDDLE-INITIAL': 'MIDDLE-INITIAL-OF',
'REPRESENTED-BY': 'REPRESENTS',
'INVERSE-OF': 'INVERSE',
'FIELD-STUDIED-BY': 'STUDIES-FIELD',
'NAME-OF': 'HAS-SURNAME',
'HAS-STANDARD-MEASURE': 'STANDARD-MEASURE-FOR',
'HAS-STATE-ADDRESS': 'STATE-ADDRESS-OF',
'ARTERIAL-SUPPLY-FOR': 'ARTERIAL-SUPPLY',
'BETWEEN-TEMPORAL': 'RELATION',
'HAS-LOWER-LIMIT': 'LOWER-LIMIT-OF',
'PARAMETRIC-RELATION': 'RELATION',
'CREATED-BY': 'CREATOR-OF',
'BENEFICIARY': 'BENEFICIARY-OF',
'HEADQUARTERS-OF': 'HAS-HEADQUARTERS',
'STUDIES-FIELD': 'FIELD-STUDIED-BY',
'HAS-MEDICAL-RISK': 'MEDICAL-RISK-OF',
'CONTROLLED-BY': 'CONTROLS',
'DISCOURSE-RELATION': 'RELATION',
'REPRESENTS': 'REPRESENTED-BY',
'THEME': 'THEME-OF',
'LANGUAGE-USED': 'LANGUAGE-OF',
'HAS-PHONE-NUMBER': 'PHONE-NUMBER-OF',
'HAS-UPPER-LIMIT': 'UPPER-LIMIT-OF',
'HAS-SIDE-EFFECT': 'RELATION',
'MEDICAL-RELATION': 'RELATION',
'INSTRUMENT': 'INSTRUMENT-OF',
'HAS-ACTIVE-INGREDIENT': 'ACTIVE-INGREDIENT-IN',
'CONTACT-INFORMATION': 'RELATION',
'HAS-CITY-OF-BIRTH': 'CITY-OF-BIRTH-OF',
'JOB-CORRESPONDS-TO-FIELD': 'FIELD-CORRESPONDS-TO-JOB',
'CONTROLS': 'CONTROLLED-BY',
'LOSER-OF': 'HAS-LOSER',
'LANGUAGE-SPOKEN-BY': 'SPEAKS-LANGUAGE',
'BORDERS': 'BORDERS-ON',
'PROPERTY-MEASURED': 'MEASURES-PROPERTY',
'INSTANCE-OF': 'INSTANCES',
'OVER-THE-PERIOD': 'TEMPORAL-PERIOD-OF',
'ACROSS-FROM': 'ACROSS',
'APPLIES-TO': 'WITHIN-SCOPE-OF-APPLICATION-OF',
'HAS-CHIEF-OPERATING-OFFICER': 'RELATION',
'TOPIC-OF': 'ABOUT-AS-TOPIC',
'HAS-COACH': 'COACH-OF',
'SCOPE': 'SCOPE-OF',
'SCOPE-OF': 'SCOPE',
'HAS-FAX-NUMBER': 'FAX-NUMBER-OF',
'WORK-EQUIPMENT-OF': 'HAS-WORK-EQUIPMENT',
'FUNCTIONS-LIKE': 'FUNCTIONS-ALIKE',
'HAS-EMAIL-ADDRESS': 'EMAIL-ADDRESS-OF',
'HAS-LOSER': 'LOSER-OF',
'HAS-CHIEF-FINANCIAL-OFFICER': 'RELATION',
'ABSOLUTE-MONTH': 'ABSOLUTE-MONTH-OF',
'PRACTITIONER-IN': 'RELATION',
'SOURCE': 'SOURCE-OF',
'FIELD-STUDIES-AREA': 'AREA-STUDIED-BY-FIELD',
'HAS-WORK-EQUIPMENT': 'WORK-EQUIPMENT-OF',
'HAS-ETHNIC-GROUP': 'ETHNIC-GROUP-OF',
'HAS-DISEASE-HISTORY': 'PAST-DISEASE-OF',
'NERVE-SUPPLY': 'NERVE-SUPPLY-OF',
'HAS-PARTNER': 'PARTNER-OF',
'OPERATOR-OF': 'OPERATED-BY',
'AUDIENCE-OF': 'HAS-AUDIENCE',
'CAUSED-BY': 'EFFECT',
'PARTNER-OF': 'HAS-PARTNER',
'HAS-DISTANT-FAMILY-RELATION': 'DISTANT-FAMILY-RELATION-OF',
'HAS-EMPLOYEE': 'EMPLOYEE-OF',
'ACTIVE-INGREDIENT-IN': 'HAS-ACTIVE-INGREDIENT',
'ONTO-INSTANCES': 'ONTO-INSTANCE-OF',
'SPOUSE-OF': 'HAS-SPOUSE',
'ABSOLUTE-MONTH-OF': 'ABSOLUTE-MONTH',
'TITLE-OF': 'HAS-TITLE',
'EXPERIENCER': 'EXPERIENCER-OF',
'GOVERNMENT-OF': 'HAS-GOVERNMENT-TYPE',
'DEPICTED-BY': 'DEPICTS',
'SYMPTOM-OF-DISEASE': 'CAUSES-SYMPTOM',
'NAMING-DATA': 'RELATION',
'NATION-ADDRESS-OF': 'HAS-NATION-ADDRESS',
'BUSINESS-COVERAGE-OF': 'HAS-BUSINESS-COVERAGE',
'CELEBRATED-IN': 'CELEBRATES',
'LOCATION-OF': 'LOCATION',
'FIRST-NAME-OF': 'HAS-PERSONAL-NAME',
'USED-BY': 'USES',
'DIRECTIONAL-RELATION': 'RELATION',
'PURPOSE': 'PURPOSE-OF',
'CASE-ROLE': 'RELATION',
'WITHIN-SCOPE-OF-APPLICATION-OF': 'APPLIES-TO',
'HEAD-OF': 'HEADED-BY',
'GREATER-THAN': 'LESS-THAN',
'LOWER-LIMIT-OF': 'HAS-LOWER-LIMIT',
'HAS-BIRTH-INFO': 'BIRTH-INFO-OF',
'FRANCHISE-OF': 'HAS-FRANCHISE',
'MEASURED-IN': 'MEASURING-UNIT-FOR',
'HAS-PERSONAL-NAME': 'FIRST-NAME-OF',
'ELEMENTS': 'RELATION',
'HEADED-BY': 'HEAD-OF',
'HAS-BUSINESS-COVERAGE': 'BUSINESS-COVERAGE-OF',
'NERVE-SUPPLY-OF': 'NERVE-SUPPLY',
'FIELD-OF-STUDY-RELATION': 'RELATION',
'PATH-OF': 'PATH',
'CONTAINED-IN': 'CONTAINS',
'HAS-OFFSPRING': 'HAS-PARENT',
'ENABLEMENT': 'ENABLED-BY',
'SUBORDINATE-TO': 'SUPERORDINATE-TO',
'EMPLOYEE-OF': 'HAS-EMPLOYEE',
'EVALUATION-STANDARD-FOR': 'EVALUATED-ACCORDING-TO',
'STYLE-RELATION': 'RELATION',
'TREATED-BY': 'TREATMENT-FOR',
'IMAGED-BY': 'CREATES-IMAGE-OF',
'PATH': 'PATH-OF',
'TEMPORAL-RELATION': 'RELATION',
'HAS-WINNER': 'WINNER-OF',
'HAS-TITLE': 'TITLE-OF',
'DESTINATION': 'DESTINATION-OF',
'DESTINATION-OF': 'DESTINATION',
'HAS-NATION-ADDRESS': 'NATION-ADDRESS-OF',
'CAUSES-SYMPTOM': 'SYMPTOM-OF-DISEASE',
'HAS-SPOUSE': 'SPOUSE-OF',
'TREATMENT-FOR': 'TREATED-BY',
'CONTAINS': 'CONTAINED-IN',
'MANUFACTURER-OF': 'MANUFACTURED-BY',
'WORN-ON': 'RELATION',
'OCCUPANT-OF': 'HAS-OCCUPANT',
'DOMAIN-OF': 'DOMAIN',
'SOURCE-OF': 'SOURCE',
'INVOLVES-OBJECT': 'USED-IN',
'CONTRAST': 'RELATION',
'LOCATION': 'LOCATION-OF',
'HAS-CREDITOR': 'RELATION',
'QUANTITY-RELATION': 'RELATION',
'ONTO-INSTANCE-OF': 'ONTO-INSTANCES',
'REFEREE-OF': 'HAS-REFEREE',
'ATTRIBUTED-TO': 'RELATION',
'TEMPORAL-PERIOD-OF': 'OVER-THE-PERIOD',
'ACCUSTOMED-TO': 'CUSTOMARY-FOR',
'HAS-LANGUAGE-OFFICIAL': 'OFFICIAL-LANGUAGE-OF',
'MEDICAL-TEST-TARGET': 'TARGETED-BY-MEDICAL-TEST',
'HAS-AUDIENCE': 'AUDIENCE-OF',
'HAS-HOLDING-COMPANY': 'HOLDING-COMPANY-OF',
'SUBSET-OF': 'RELATION',
'HAS-CAPITAL': 'RELATION',
'CUSTOMER-OF': 'HAS-CUSTOMER',
'STATE-ADDRESS-OF': 'HAS-STATE-ADDRESS',
'IN-LAW-OF': 'HAS-IN-LAW',
'CREATOR-OF': 'CREATED-BY',
'CREATES-IMAGE-OF': 'IMAGED-BY',
'REPRESENTATIVE-OF': 'HAS-REPRESENTATIVE'};

var intermediateExample = ">>> sentence_analyzer(inp7o,log=1)\n Input Sentence = John gave Mary a book.\n SUBJECT : 1 gave, 0 John\n  ROOT : -1 , 1 gave\n  INDIRECTOBJECT : 1 gave, 2 Mary\n ART : 4 book, 3 a\n DIRECTOBJECT : 1 gave, 4 book\nWord = GIVE is found in Lexicon, number of senses = 31\nWord = GIVE is found in 2 sense(s) as a synonym.\nSemantic constraint CRIMINAL-ROLE for HUMAN in SUBJECT had failed.\n Skipping GIVE-V4 - JOHN-N1 pair.\nRequired word(s) UP does NOT match input MARY\nRequired word(s) UP does NOT match input A\nRequired word(s) UP does NOT match input BOOK\n  Skipping GIVE-V21 - JOHN-N1 pair.\nRequired word(s) OUT does NOT match input MARY\nRequired word(s) OUT does NOT match input A\nRequired word(s) OUT does NOT match input BOOK\n  Skipping GIVE-V32 - JOHN-N1 pair.\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V13\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V30\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V24\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V9\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n Skipping GIVE-V20\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V18\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V7\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n Skipping GIVE-V14\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V17\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V15\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V10\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V11\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping GIVE-V5\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC \n  Skipping GIVE-V6\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n Skipping GIVE-V22\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n  Skipping ADMINISTER-V1\ninput syn element INDIRECTOBJECT not found in lex entry SYN-STRUC\n Skipping PROVIDE-V1\nWord = BOOK is found in Lexicon, number of senses = 5\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nRequired word(s) ADVICE does NOT match input BOOK\n Skipping GIVE-V25 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nRequired word(s) INSTRUCTION does NOT match input BOOK\n  Skipping GIVE-V19 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nRequired word(s) ADVICE does NOT match input BOOK\n Skipping GIVE-V29 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V ) \n Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nSemantic constraint EVENT for BOOK in DIRECTOBJECT had failed.\n  Skipping GIVE-V2 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nRequired word(s) ['OR', 'MYSELF', 'YOURSELF', 'HIMSELF', 'HERSELF', 'OURSELVES', 'YOURSELVES', 'THEMSELVES', 'ONESELF'] does NOT match input BOOK\n Skipping GIVE-V12 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nRequired word(s) ['OR', 'ADVICE', 'RECOMMENDATION', 'SUGGESTION'] does NOT match input BOOK\n Skipping GIVE-V31 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nSemantic constraint COMMUNICABLE-DISEASE for BOOK in DIRECTOBJECT had failed.\n Skipping GIVE-V16 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nRequired word(s) CALL does NOT match input BOOK\n Skipping GIVE-V27 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V ) \n Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nSemantic constraint EVENT for BOOK in DIRECTOBJECT had failed.\n  Skipping GIVE-V1 - BOOK-N1 pair.\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V1\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V2\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V4\nPOS of the word BOOK ( N ) does NOT match POS of lexicon entry ( V )\n  Skipping BOOK-V3\nRequired word(s) ['OR', 'ADVICE', 'RECOMMENDATION', 'SUGGESTION'] does NOT match input BOOK\n Skipping GIVE-V28 - BOOK-N1 pair.\nSense GIVE-V8 : required syntactic role ( COMP ) is missing in the input sentence\nRemoving a false positive result: {0: 'JOHN-N1', 1: 'GIVE-V8', 2: 'MARY-N1', 4: 'BOOK-N1'}\n-- Final result: Length= 2\n{\n\t'Step': 'final',\n\t'results': [\n\t\t{\n\t\t\t'TMR': {\n\t\t\t\t'BOOK-1': {\n\t\t\t\t\t'THEME-OF': 'INFORM-1',\n\t\t\t\t\t'concept': 'BOOK',\n\t\t\t\t\t'from-sense': 'BOOK-N1',\n\t\t\t\t\t'token': 'book',\n\t\t\t\t\t'word-ind': 4\n\t\t\t\t},\n\t\t\t\t'HUMAN-1': {\n\t\t\t\t\t'AGENT-OF': 'INFORM-1',\n\t\t\t\t\t'concept': 'HUMAN',\n\t\t\t\t\t'from-sense': 'JOHN-N1',\n\t\t\t\t\t'lex-source': 'NER',\n\t\t\t\t\t'token': 'John',\n\t\t\t\t\t'word-ind': 0\n\t\t\t\t},\n\t\t\t\t'HUMAN-2': {\n\t\t\t\t\t'BENEFICIARY-OF': 'INFORM-1',\n\t\t\t\t\t'concept': 'HUMAN',\n\t\t\t\t\t'from-sense': 'MARY-N1',\n\t\t\t\t\t'lex-source': 'NER',\n\t\t\t\t\t'token': 'Mary',\n\t\t\t\t\t'word-ind': 2\n\t\t\t\t},\n\t\t\t\t'INFORM-1': {\n\t\t\t\t\t'AGENT': 'HUMAN-1',\n\t\t\t\t\t'BENEFICIARY': 'HUMAN-2',\n\t\t\t\t\t'THEME': 'BOOK-1',\n\t\t\t\t\t'TIME': [\n\t\t\t\t\t\t'<',\n\t\t\t\t\t\t'FIND-ANCHOR-TIME'\n\t\t\t\t\t],\n\t\t\t\t\t'concept': 'INFORM',\n\t\t\t\t\t'from-sense': 'GIVE-V26',\n\t\t\t\t\t'syn-roles': [\n\t\t\t\t\t\t'SUBJECT',\n\t\t\t\t\t\t'INDIRECTOBJECT',\n\t\t\t\t\t\t'DIRECTOBJECT'\n\t\t\t\t\t],\n\t\t\t\t\t'token': 'gave',\n\t\t\t\t\t'word-ind': 1\n\t\t\t\t}\n\t\t\t},\n\t\t\t'concept_counts': {\n\t\t\t\t'BOOK': {\n\t\t\t\t\t'count': 1,\n\t\t\t\t\t'word-ind': [\n\t\t\t\t\t\t4\n\t\t\t\t\t]\n\t\t\t\t},\n\t\t\t\t'HUMAN': {\n\t\t\t\t\t'count': 2,\n\t\t\t\t\t'word-ind': [\n\t\t\t\t\t\t0,\n\t\t\t\t\t\t2\n\t\t\t\t\t]\n\t\t\t\t},\n\t\t\t\t'INFORM': {\n\t\t\t\t\t'count': 1,\n\t\t\t\t\t'word-ind': [\n\t\t\t\t\t\t1\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t},\n\t\t\t'words': {\n\t\t\t\t'0': 'JOHN-N1',\n\t\t\t\t'1': 'GIVE-V26',\n\t\t\t\t'2': 'MARY-N1',\n\t\t\t\t'4': 'BOOK-N1'\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t'TMR': {\n\t\t\t\t'BOOK-1': {\n\t\t\t\t\t'THEME-OF': 'GIVE-1',\n\t\t\t\t\t'concept': 'BOOK',\n\t\t\t\t\t'from-sense': 'BOOK-N1',\n\t\t\t\t\t'token': 'book',\n\t\t\t\t\t'word-ind': 4\n\t\t\t\t},\n\t\t\t\t'GIVE-1': {\n\t\t\t\t\t'AGENT': 'HUMAN-1',\n\t\t\t\t\t'BENEFICIARY': 'HUMAN-2',\n\t\t\t\t\t'THEME': 'BOOK-1',\n\t\t\t\t\t'TIME': [\n\t\t\t\t\t\t'<',\n\t\t\t\t\t\t'FIND-ANCHOR-TIME'\n\t\t\t\t\t],\n\t\t\t\t\t'concept': 'GIVE',\n\t\t\t\t\t'from-sense': 'GIVE-V3',\n\t\t\t\t\t'syn-roles': [\n\t\t\t\t\t\t'SUBJECT',\n\t\t\t\t\t\t'INDIRECTOBJECT',\n\t\t\t\t\t\t'DIRECTOBJECT'\n\t\t\t\t\t],\n\t\t\t\t\t'token': 'gave',\n\t\t\t\t\t'word-ind': 1\n\t\t\t\t},\n\t\t\t\t'HUMAN-1': {\n\t\t\t\t\t'AGENT-OF': 'GIVE-1',\n\t\t\t\t\t'concept': 'HUMAN',\n\t\t\t\t\t'from-sense': 'JOHN-N1',\n\t\t\t\t\t'lex-source': 'NER',\n\t\t\t\t\t'token': 'John',\n\t\t\t\t\t'word-ind': 0\n\t\t\t\t},\n\t\t\t\t'HUMAN-2': {\n\t\t\t\t\t'BENEFICIARY-OF': 'GIVE-1',\n\t\t\t\t\t'concept': 'HUMAN',\n\t\t\t\t\t'from-sense': 'MARY-N1',\n\t\t\t\t\t'lex-source': 'NER',\n\t\t\t\t\t'token': 'Mary',\n\t\t\t\t\t'word-ind': 2\n\t\t\t\t}\n\t\t\t},\n\t\t\t'concept_counts': {\n\t\t\t\t'BOOK': {\n\t\t\t\t\t'count': 1,\n\t\t\t\t\t'word-ind': [\n\t\t\t\t\t\t4\n\t\t\t\t\t]\n\t\t\t\t},\n\t\t\t\t'GIVE': {\n\t\t\t\t\t'count': 1,\n\t\t\t\t\t'word-ind': [\n\t\t\t\t\t\t1\n\t\t\t\t\t]\n\t\t\t\t},\n\t\t\t\t'HUMAN': {\n\t\t\t\t\t'count': 2,\n\t\t\t\t\t'word-ind': [\n\t\t\t\t\t\t0,\n\t\t\t\t\t\t2\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t},\n\t\t\t'words': {\n\t\t\t\t'0': 'JOHN-N1',\n\t\t\t\t'1': 'GIVE-V3',\n\t\t\t\t'2': 'MARY-N1',\n\t\t\t\t'4': 'BOOK-N1'\n\t\t\t}\n\t\t}\n\t],\n\t'sent-num': 1,\n\t'sentence': 'John gave Mary a book.',\n\t'timestamp': '2016-Jan-25 13:40:18'\n}\n[True, 2]\n>>>";

module.exports = {
  port: 3000,
  pythonPort: 8000,
  exampleData: exampleTMR,
  exampleIntermediate: intermediateExample,
  isCapitalized: function(str) {
    return str == str.toUpperCase();
  },
  richLogging: {
    info: function(message) {
      console.log(message || "-");
    },
    attn: function(message) {
      console.log((message || "-").cyan);
    },
    success: function(message) {
      console.log((message || "-").green);
    },
    error: function(message) {
      console.log((message || "-").red);
    },
    warning: function(message) {
      console.log((message || "-").orange);
    }
  }
};
